version: '3.1'
services:
  mariadb:
    image: mariadb
    container_name: nodevader-mariadb
    restart: always
    ports:
      - 3333:3306
    environment:
      - MYSQL_DATABASE=nodevader
      - MYSQL_USER=nodevader
      - MYSQL_PASSWORD=nodevader
      - MYSQL_ROOT_PASSWORD=nodevader
    volumes:
      - ./docker/storage/mariadb:/var/lib/mysql
      - ./docker/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
  flyway:
    container_name: nodevader-flyway
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:mysql://mariadb/nodevader -schemas=nodevader -user=nodevader -password=nodevader -connectRetries=10 migrate
    volumes:
      - ./docker/migrations:/flyway/sql
    depends_on:
      - mariadb
  api:
    build: ./docker/bin/nodejs
    image: api
    container_name: nodevader-api
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - 8888:3000
    volumes:
      - .:/app
    depends_on:
      - flyway
